// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwBTLRMtCPyzG9m0Q2-3ppe8tMDh_0-oU',
    appId: '1:154598618355:android:b8896de3ae844726fdf386',
    messagingSenderId: '154598618355',
    projectId: 'nasa-space-app-si',
    databaseURL: 'https://nasa-space-app-si-default-rtdb.firebaseio.com',
    storageBucket: 'nasa-space-app-si.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmz3sJ28aHthzGko1SaYPsggNC3pD9r24',
    appId: '1:154598618355:ios:f1f8429a785e27adfdf386',
    messagingSenderId: '154598618355',
    projectId: 'nasa-space-app-si',
    databaseURL: 'https://nasa-space-app-si-default-rtdb.firebaseio.com',
    storageBucket: 'nasa-space-app-si.appspot.com',
    iosClientId: '154598618355-od05po825kdts8i88pc5rru5haqt3l23.apps.googleusercontent.com',
    iosBundleId: 'com.tminuszero.team',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzqdw-3ROaTntAEOf7CjX-d2tSQObeHoM',
    appId: '1:154598618355:web:2c3217a9d53dbaedfdf386',
    messagingSenderId: '154598618355',
    projectId: 'nasa-space-app-si',
    authDomain: 'nasa-space-app-si.firebaseapp.com',
    databaseURL: 'https://nasa-space-app-si-default-rtdb.firebaseio.com',
    storageBucket: 'nasa-space-app-si.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmz3sJ28aHthzGko1SaYPsggNC3pD9r24',
    appId: '1:154598618355:ios:a54aab5ddee689b7fdf386',
    messagingSenderId: '154598618355',
    projectId: 'nasa-space-app-si',
    databaseURL: 'https://nasa-space-app-si-default-rtdb.firebaseio.com',
    storageBucket: 'nasa-space-app-si.appspot.com',
    iosClientId: '154598618355-d3l2hm73lteclr3n7ofu9923p17unbr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasaSpaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzqdw-3ROaTntAEOf7CjX-d2tSQObeHoM',
    appId: '1:154598618355:web:204b820e1bcd82ddfdf386',
    messagingSenderId: '154598618355',
    projectId: 'nasa-space-app-si',
    authDomain: 'nasa-space-app-si.firebaseapp.com',
    databaseURL: 'https://nasa-space-app-si-default-rtdb.firebaseio.com',
    storageBucket: 'nasa-space-app-si.appspot.com',
  );

}